import type { CommunityPost, CommunityPhoto, CityHotSpot } from "@/lib/community/types";

export const mockPosts: CommunityPost[] = [
  {
    id: "p1",
    type: "trip",
    author: {
      id: "u1",
      displayName: "Sarah M.",
      avatarInitials: "SM",
      avatarId: "bamboo-hat",
      country: "🇦🇺",
      memberTierId: "silk-road-insider",
    },
    title: "10 Days Beijing → Xi'an → Chengdu — Perfect First China Trip",
    body: "Just got back from my first China trip and I'm already planning a return visit! The VisePanda AI helped me balance the pace perfectly — no rushing between sites. Highlights: watching sunrise at the Great Wall with almost no crowds (Mutianyu, arrived at 7am), eating hand-pulled noodles in Xi'an's Muslim Quarter for ¥12, and getting to watch giant pandas at the Chengdu base during morning feeding time.",
    cities: ["Beijing", "Xi'an", "Chengdu"],
    daysCount: 10,
    coverEmoji: "🏯",
    likes: 142,
    comments: 23,
    saved: 48,
    createdAt: "2026-06-28",
    tags: ["first-timer", "culture", "food", "pandas"],
  },
  {
    id: "p2",
    type: "tip",
    author: {
      id: "u2",
      displayName: "James K.",
      avatarInitials: "JK",
      avatarId: "compass",
      country: "🇬🇧",
      memberTierId: "panda-explorer",
    },
    title: "How to Use Alipay as a Foreigner — 2026 Guide",
    body: "The process has gotten much easier! Download Alipay, tap 'International version', link your Visa/Mastercard, and set up face verification. You'll get a ¥2000 daily spending limit which is more than enough for most days. Key tip: do this before you land in China — the verification process needs a stable connection and can take 10 minutes. Once set up, almost everywhere accepts it including small street food stalls.",
    cities: ["Shanghai", "Beijing"],
    coverEmoji: "💳",
    likes: 98,
    comments: 41,
    saved: 52,
    createdAt: "2026-06-27",
    tags: ["payment", "alipay", "practical"],
  },
  {
    id: "p3",
    type: "trip",
    author: {
      id: "u3",
      displayName: "Mia T.",
      avatarInitials: "MT",
      avatarId: "tea-cup",
      country: "🇸🇬",
      memberTierId: "silk-road-insider",
    },
    title: "Weekend in Hangzhou — West Lake and Beyond",
    body: "Hangzhou is absolutely stunning and only 45 minutes from Shanghai by high-speed rail. Rented a bicycle around West Lake early morning — the mist on the water was magical. Don't miss Longjing Village for fresh dragon well tea picked in April. The night market near Hefang Street has some of the best street food I've tried in China.",
    cities: ["Hangzhou"],
    daysCount: 3,
    coverEmoji: "🌊",
    likes: 76,
    comments: 12,
    saved: 19,
    createdAt: "2026-06-25",
    tags: ["weekend", "nature", "tea", "shanghai-daytrip"],
  },
  {
    id: "p4",
    type: "tip",
    author: {
      id: "u4",
      displayName: "Luca B.",
      avatarInitials: "LB",
      avatarId: "red-scarf",
      country: "🇮🇹",
      memberTierId: "panda-explorer",
    },
    title: "Best Street Food in Shanghai's French Concession",
    body: "Wulumuqi Road and Anfu Road have the best morning food scene. Get scallion pancakes (葱油饼) for ¥5, freshly made jianbing from the cart outside the Wulumuqi market for ¥12, and finish with a soy milk and youtiao combo for ¥8. Avoid the tourist-facing spots on Nanjing Road for breakfast — they're overpriced and not as good.",
    cities: ["Shanghai"],
    coverEmoji: "🥟",
    likes: 115,
    comments: 29,
    saved: 63,
    createdAt: "2026-06-23",
    tags: ["food", "street-food", "shanghai", "budget"],
  },
  {
    id: "p5",
    type: "trip",
    author: {
      id: "u5",
      displayName: "Priya N.",
      avatarInitials: "PN",
      avatarId: "backpack",
      country: "🇮🇳",
      memberTierId: "dragon-pass",
    },
    title: "Chongqing Hot Pot Pilgrimage — 5 Days",
    body: "Came specifically for the hot pot and was not disappointed. The Lijia Restaurant near Hongyadong has the authentic Chongqing-style broth — they'll let you choose your spice level, but even 'mild' is hotter than anything I've had in Beijing. The city itself is stunning, built on cliffs along the Yangtze. The cable car across the river costs ¥5 and gives you the best city views for almost nothing.",
    cities: ["Chongqing"],
    daysCount: 5,
    coverEmoji: "🌶️",
    likes: 89,
    comments: 17,
    saved: 31,
    createdAt: "2026-06-20",
    tags: ["hotpot", "food", "chongqing", "spicy"],
  },
  {
    id: "p6",
    type: "trip",
    author: {
      id: "u6",
      displayName: "Tom W.",
      avatarInitials: "TW",
      avatarId: "ink-brush",
      country: "🇺🇸",
      memberTierId: "visepanda-concierge",
    },
    title: "Shanghai Art Week + Food Tour — A 7-Day Deep Dive",
    body: "Timed my trip around the Shanghai Art Week at the end of November. The Long Museum West Bund and Tank Shanghai were incredible — contemporary Chinese art at a world-class level. Between gallery visits, the whole area around the West Bund waterfront is perfect for walking. Restaurant tip: Da Dong's Shanghai location is worth the splurge for Peking Duck if you want a high-end version outside Beijing.",
    cities: ["Shanghai"],
    daysCount: 7,
    coverEmoji: "🎨",
    likes: 63,
    comments: 8,
    saved: 27,
    createdAt: "2026-06-18",
    tags: ["art", "culture", "shanghai", "food"],
  },
];

export const mockPhotos: CommunityPhoto[] = [
  {
    id: "ph1",
    author: {
      id: "u1",
      displayName: "Sarah M.",
      avatarInitials: "SM",
      avatarId: "bamboo-hat",
      country: "🇦🇺",
      memberTierId: "silk-road-insider",
    },
    caption: "Sunrise at Mutianyu — arrived at 7am and had the wall almost to ourselves",
    city: "Beijing",
    locationName: "Mutianyu Great Wall",
    emoji: "🏔️",
    likes: 234,
    createdAt: "2026-06-28",
  },
  {
    id: "ph2",
    author: {
      id: "u3",
      displayName: "Mia T.",
      avatarInitials: "MT",
      avatarId: "tea-cup",
      country: "🇸🇬",
      memberTierId: "silk-road-insider",
    },
    caption: "West Lake morning mist — worth waking up at 6am for",
    city: "Hangzhou",
    locationName: "West Lake",
    emoji: "🌊",
    likes: 187,
    createdAt: "2026-06-25",
  },
  {
    id: "ph3",
    author: {
      id: "u5",
      displayName: "Priya N.",
      avatarInitials: "PN",
      avatarId: "backpack",
      country: "🇮🇳",
      memberTierId: "dragon-pass",
    },
    caption: "The lights of Hongyadong reflected on the Yangtze at night",
    city: "Chongqing",
    locationName: "Hongyadong",
    emoji: "🌆",
    likes: 156,
    createdAt: "2026-06-20",
  },
  {
    id: "ph4",
    author: {
      id: "u2",
      displayName: "James K.",
      avatarInitials: "JK",
      avatarId: "compass",
      country: "🇬🇧",
      memberTierId: "panda-explorer",
    },
    caption: "The Bund at dusk — classic but never gets old",
    city: "Shanghai",
    locationName: "The Bund",
    emoji: "🌇",
    likes: 312,
    createdAt: "2026-06-27",
  },
  {
    id: "ph5",
    author: {
      id: "u7",
      displayName: "Anna L.",
      avatarInitials: "AL",
      avatarId: "red-scarf",
      country: "🇩🇪",
      memberTierId: "panda-explorer",
    },
    caption: "Giant pandas at morning feeding — absolute chaos and joy",
    city: "Chengdu",
    locationName: "Giant Panda Base",
    emoji: "🐼",
    likes: 421,
    createdAt: "2026-06-26",
  },
  {
    id: "ph6",
    author: {
      id: "u4",
      displayName: "Luca B.",
      avatarInitials: "LB",
      avatarId: "red-scarf",
      country: "🇮🇹",
      memberTierId: "panda-explorer",
    },
    caption: "Jianbing breakfast cart — ¥12 and the best thing I ate all trip",
    city: "Shanghai",
    locationName: "Wulumuqi Road",
    emoji: "🥞",
    likes: 98,
    createdAt: "2026-06-23",
  },
  {
    id: "ph7",
    author: {
      id: "u8",
      displayName: "Chen R.",
      avatarInitials: "CR",
      avatarId: "compass",
      country: "🇨🇦",
      memberTierId: "silk-road-insider",
    },
    caption: "Terra cotta warriors in Pit 1 — the scale is overwhelming",
    city: "Xi'an",
    locationName: "Terracotta Army Museum",
    emoji: "⚔️",
    likes: 278,
    createdAt: "2026-06-22",
  },
  {
    id: "ph8",
    author: {
      id: "u6",
      displayName: "Tom W.",
      avatarInitials: "TW",
      avatarId: "ink-brush",
      country: "🇺🇸",
      memberTierId: "visepanda-concierge",
    },
    caption: "Tank Shanghai — world class contemporary art by the river",
    city: "Shanghai",
    locationName: "Tank Shanghai",
    emoji: "🎨",
    likes: 74,
    createdAt: "2026-06-18",
  },
];

export const mockHotSpots: CityHotSpot[] = [
  // Beijing
  {
    id: "h1", cityId: "beijing", cityName: "Beijing",
    name: "Jingshan Park sunrise", chinese: "景山公园", category: "attraction",
    rating: 4.8, reviewCount: 312,
    tip: "Arrive 30 min before sunrise for the classic Forbidden City rooftop view. Free entry with park card.",
    emoji: "🌅",
  },
  {
    id: "h2", cityId: "beijing", cityName: "Beijing",
    name: "Guijie Hot Pot Street", chinese: "簋街", category: "food",
    rating: 4.6, reviewCount: 891,
    tip: "Open past midnight, full of locals. Order the classic Sichuan broth with lamb slices.",
    emoji: "🍲",
  },
  {
    id: "h3", cityId: "beijing", cityName: "Beijing",
    name: "Nanluoguxiang Alley", chinese: "南锣鼓巷", category: "hidden",
    rating: 4.4, reviewCount: 567,
    tip: "Skip the main drag — the hutong side streets (Banchang, Mao'er) are where the real old Beijing is.",
    emoji: "🏘️",
  },
  // Shanghai
  {
    id: "h4", cityId: "shanghai", cityName: "Shanghai",
    name: "Tianzifang art lanes", chinese: "田子坊", category: "hidden",
    rating: 4.5, reviewCount: 743,
    tip: "Come on weekday mornings before 10am to avoid crowds. The side alleys have independent shops worth exploring.",
    emoji: "🎭",
  },
  {
    id: "h5", cityId: "shanghai", cityName: "Shanghai",
    name: "Xiaolongbao at Din Tai Fung", chinese: "鼎泰丰小笼包", category: "food",
    rating: 4.9, reviewCount: 2103,
    tip: "Queue at the IFC Mall branch early — it opens at 11am and queues form by 10:45. Worth every minute.",
    emoji: "🥟",
  },
  {
    id: "h6", cityId: "shanghai", cityName: "Shanghai",
    name: "West Bund Waterfront", chinese: "西岸滨江", category: "attraction",
    rating: 4.7, reviewCount: 456,
    tip: "Walk south from Longhua metro. Great museums, free river views, and zero tourist crowds.",
    emoji: "🏛️",
  },
  // Chengdu
  {
    id: "h7", cityId: "chengdu", cityName: "Chengdu",
    name: "Jinli Ancient Street", chinese: "锦里古街", category: "attraction",
    rating: 4.3, reviewCount: 892,
    tip: "Best in the evening when lanterns are lit. Arrive hungry — the rabbit head and glutinous rice cake are must-tries.",
    emoji: "🏮",
  },
  {
    id: "h8", cityId: "chengdu", cityName: "Chengdu",
    name: "Mapo tofu at Chen Mapo", chinese: "陈麻婆豆腐", category: "food",
    rating: 4.8, reviewCount: 1234,
    tip: "The original restaurant near Qingyang District. Order the signature mapo tofu and beef in bean sauce. Lunch only.",
    emoji: "🌶️",
  },
  // Xi'an
  {
    id: "h9", cityId: "xian", cityName: "Xi'an",
    name: "Muslim Quarter Night Market", chinese: "回民街夜市", category: "food",
    rating: 4.7, reviewCount: 1567,
    tip: "Arrive after 6pm for peak atmosphere. Must-eat: roujiamo (¥10), biang biang noodles (¥15), and pomegranate juice.",
    emoji: "🌙",
  },
  {
    id: "h10", cityId: "xian", cityName: "Xi'an",
    name: "City Wall bike ride", chinese: "古城墙骑行", category: "attraction",
    rating: 4.6, reviewCount: 678,
    tip: "Rent a bike at the South Gate (南门) and do the full 14km loop. Takes about 90 minutes at a relaxed pace.",
    emoji: "🚲",
  },
  // Hangzhou
  {
    id: "h11", cityId: "hangzhou", cityName: "Hangzhou",
    name: "Longjing tea village", chinese: "龙井村", category: "hidden",
    rating: 4.5, reviewCount: 345,
    tip: "Take bus 27 from Yugu Road. Buy directly from farmers for fresher tea at lower prices than city shops.",
    emoji: "🍵",
  },
  {
    id: "h12", cityId: "hangzhou", cityName: "Hangzhou",
    name: "Hefang Street snacks", chinese: "河坊街", category: "food",
    rating: 4.4, reviewCount: 892,
    tip: "Try the walnut cakes (核桃酥), vinegar-braised pork knuckle, and West Lake lotus root starch soup.",
    emoji: "🥮",
  },
];

export const HOT_SPOT_CITIES = [
  { id: "beijing", name: "Beijing" },
  { id: "shanghai", name: "Shanghai" },
  { id: "chengdu", name: "Chengdu" },
  { id: "xian", name: "Xi'an" },
  { id: "hangzhou", name: "Hangzhou" },
];
