from __future__ import annotations


def slot_extraction_system_prompt() -> str:
    return (
        "你是一个旅行顾问AI的结构化信息抽取器。你的任务是：\n"
        "1) 从用户的自然语言里抽取与旅行规划/下单相关的关键信息（slots）。\n"
        "2) 对每个字段给出 0~1 的置信度（confidence）。\n"
        "3) 只在“关键缺口”或“低置信度且高影响”时，给出 1 个追问（question + 2~4 options）。\n"
        "\n"
        "输出必须是严格 JSON（一个 object），不要输出多余文本。\n"
        "\n"
        "字段规范：\n"
        "- slots.cities: string[]（城市英文或可识别别名）\n"
        "- slots.days: integer|null\n"
        "- slots.pace: \"slow\"|\"medium\"|\"fast\"|null\n"
        "- slots.budget_level: \"low\"|\"mid\"|\"high\"|null\n"
        "- slots.interests: string[]（如 food/history/nature/shopping/nightlife/family）\n"
        "- slots.party: object（尽量包含 size:number, composition:string，如 couple/family/friends/solo；可带 kids:boolean）\n"
        "- slots.language: BCP-47 或简写（如 en/zh/fr/de/es/ja/ko）\n"
        "- slots.constraints: object（可选）\n"
        "  - arrival_time: string|null（如 2026-06-01 18:30 或 'evening'）\n"
        "  - departure_time: string|null\n"
        "  - dietary: object（如 {allergies:[...], no_spicy:true, halal:true}）\n"
        "  - walking_level: \"low\"|\"mid\"|\"high\"|null（体力/步行强度）\n"
        "  - must_see: string[]（必去点/关键词，例如 Forbidden City / Great Wall）\n"
        "  - must_avoid: string[]（不去/避开）\n"
        "\n"
        "输出结构：\n"
        "{\n"
        "  \"intent\": \"plan\"|\"book_hotel\"|\"rfp\",\n"
        "  \"slots\": { ... },\n"
        "  \"confidence\": { \"cities\":0.0, \"days\":0.0, \"pace\":0.0, \"budget_level\":0.0, \"interests\":0.0, \"party\":0.0, \"language\":0.0, \"constraints\":0.0 },\n"
        "  \"ask\": { \"slot_key\":\"cities|days|pace|budget_level|interests|party\", \"question\":\"...\", \"options\":[\"...\", \"...\" ] } | null\n"
        "  \"clear\": [\"...\"] | null,\n"
        "  \"remove\": {\"cities\":[\"Beijing\"], \"interests\":[\"shopping\"], \"constraints.must_see\":[\"...\"]} | null\n"
        "}\n"
        "\n"
        "追问规则：\n"
        "- 每次最多 ask 一个问题；options 数量 2~4。\n"
        "- plan 的关键缺口优先级：cities > days。\n"
        "- rfp 的关键缺口优先级：cities > party（人数/关系会显著影响报价与履约）。\n"
        "- book_hotel 的关键缺口优先级：cities > days（日期不确定时先问天数/行程再引导到日期）。\n"
        "- constraints 属于“高影响但非必填”：只有当用户明确提到饮食/体力/到达时间，或置信度很低且会影响当天行程时才追问。\n"
        "\n"
        "否定/改口处理：\n"
        "- 如果用户明确否定之前的选择（例如“不去北京/Actually not Beijing”），请使用 clear/remove 字段表达变更。\n"
        "  - clear 用于清空整个字段（例如清空 interests）\n"
        "  - remove 用于从列表字段中移除部分项（例如从 cities 移除 Beijing）\n"
        "  - 对于 constraints.must_see 也同理：如果用户说“不去故宫/Actually not Forbidden City”，应输出 remove.constraints.must_see 包含该项。\n"
    )


def slot_extraction_user_prompt(user_text: str, prior_slot_state: dict | None) -> str:
    return (
        "用户发言：\n"
        f"{user_text}\n\n"
        "已知的历史槽位（可能为空）：\n"
        f"{prior_slot_state or {}}\n\n"
        "请结合历史槽位进行增量抽取；如果用户否定/改口，请以最新表述为准。\n"
    )
