package space.go2china.visepanda.butler.agent;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import space.go2china.visepanda.butler.model.CanvasPatch;

class CanvasPatchNormalizerTest {
    private final ObjectMapper objectMapper = new ObjectMapper();
    private final CanvasPatchNormalizer normalizer = new CanvasPatchNormalizer(objectMapper);

    @Test
    void wrapsStringHighlightsFromRealModelShape() throws Exception {
        CanvasPatch patch = parse("""
                {
                  "intent": "create_trip",
                  "assistantMessage": "I drafted a compact Shanghai day.",
                  "assistantResponse": {
                    "headline": "Shanghai intro",
                    "body": "A simple first-day route.",
                    "highlights": "Yu Garden, Bund, Shanghai Museum, French Concession",
                    "watchOut": null,
                    "nextStep": "Review the route.",
                    "followUp": "I can also suggest hotel options near the Bund."
                  },
                  "reason": "Generated by DeepSeek."
                }
                """);

        assertThat(patch.assistantResponse().highlights())
                .containsExactly("Yu Garden, Bund, Shanghai Museum, French Concession");
        assertThat(patch.assistantResponse().followUp())
                .containsExactly("I can also suggest hotel options near the Bund.");
    }

    @Test
    void addsEmptyBlocksWhenDayOmitsBlocks() throws Exception {
        CanvasPatch patch = parse("""
                {
                  "intent": "create_trip",
                  "assistantMessage": "I drafted a day.",
                  "assistantResponse": {
                    "headline": "Shanghai intro",
                    "body": "A simple first-day route.",
                    "highlights": ["Bund"],
                    "watchOut": null,
                    "nextStep": "Review the route."
                  },
                  "days": [
                    {"day": 1, "city": "Shanghai", "pace": "Balanced", "food": null}
                  ],
                  "reason": "Generated by test."
                }
                """);

        assertThat(patch.days()).hasSize(1);
        assertThat(patch.days().get(0).blocks()).isEmpty();
        assertThat(patch.days().get(0).food()).isEmpty();
    }

    private CanvasPatch parse(String json) throws Exception {
        JsonNode normalized = normalizer.normalize(objectMapper.readTree(json));
        return objectMapper.treeToValue(normalized, CanvasPatch.class);
    }
}
