"""Smart packing list — generated by destination/season/days/activity"""
PACKING_CATEGORIES = {
    "essentials": {"name": "Documents & Essentials (证件/必备)", "icon": "🪪", "items": [
        {"name": "Passport/ID card (护照/身份证)", "condition": "always"},
        {"name": "Visa/Entry documents (签证/入境文件)", "condition": "international"},
        {"name": "Hotel booking (print) (酒店预订单)", "condition": "always"},
        {"name": "Flight/train tickets (electronic/print) (机票/火车票)", "condition": "always"},
        {"name": "Travel insurance (旅行保险单)", "condition": "always"},
        {"name": "Bank card — UnionPay/Visa/Master (银行卡)", "condition": "always"},
        {"name": "Cash ¥500–1,000 (现金)", "condition": "always"},
        {"name": "Phone + charging cable (手机+充电线)", "condition": "always"},
    ]},
    "clothing": {"name": "Clothing (衣物)", "icon": "👕", "items": [
        {"name": "T-shirts/shirts — 1 per day (T恤/衬衫)", "condition": "always"},
        {"name": "Long pants/shorts (长裤/短裤)", "condition": "always"},
        {"name": "Jacket/windbreaker (外套/冲锋衣)", "condition": "always"},
        {"name": "Underwear/socks — 1 set per day (内衣袜)", "condition": "always"},
        {"name": "Comfortable walking shoes (舒适步行鞋)", "condition": "always"},
        {"name": "Sandals/slippers (凉鞋/拖鞋)", "condition": "summer"},
        {"name": "Down jacket/thermal underwear (羽绒服/保暖内衣)", "condition": "winter"},
        {"name": "Sun-protection clothing/hat (防晒衣/帽子)", "condition": "summer"},
        {"name": "Swimsuit (泳衣)", "condition": "beach"},
        {"name": "Raincoat/umbrella (雨衣/雨伞)", "condition": "rainy"},
    ]},
    "toiletries": {"name": "Toiletries & Medicine (洗漱/药品)", "icon": "🧴", "items": [
        {"name": "Toothbrush/toothpaste/face wash (牙刷/牙膏/洗面奶)", "condition": "always"},
        {"name": "Shampoo/shower gel — travel size (洗发水/沐浴露)", "condition": "always"},
        {"name": "Sunscreen SPF50+ (防晒霜)", "condition": "summer"},
        {"name": "Insect repellent (驱蚊液)", "condition": "summer"},
        {"name": "Cold medicine/stomach medicine (感冒药/肠胃药)", "condition": "always"},
        {"name": "Band-aids/antiseptic wipes (创可贴/消毒棉片)", "condition": "always"},
        {"name": "Motion-sickness medicine (晕车药)", "condition": "long_trip"},
        {"name": "Altitude-sickness medicine — Rhodiola rosea (高反药/红景天)", "condition": "high_altitude"},
        {"name": "Contact lenses/glasses (隐形眼镜/眼镜)", "condition": "always"},
    ]},
    "electronics": {"name": "Electronics (电子设备)", "icon": "🔌", "items": [
        {"name": "Power bank ≤20,000mAh (充电宝)", "condition": "always"},
        {"name": "Travel adaptor — 3-pin flat (转换插头/三孔扁头)", "condition": "always"},
        {"name": "Headphones (耳机)", "condition": "always"},
        {"name": "Camera/GoPro (相机/GoPro)", "condition": "optional"},
        {"name": "Car charger (车载充电器)", "condition": "road_trip"},
        {"name": "VPN/SIM card/eSIM (VPN/上网卡/eSIM)", "condition": "international"},
    ]},
    "misc": {"name": "Other (其他)", "icon": "📦", "items": [
        {"name": "Thermos/flask (保温杯)", "condition": "always"},
        {"name": "Tissues/wet wipes (纸巾/湿巾)", "condition": "always"},
        {"name": "Snacks (零食)", "condition": "long_trip"},
        {"name": "Neck pillow/eye mask/earplugs (颈枕/眼罩/耳塞)", "condition": "long_trip"},
        {"name": "Foldable shopping bag (折叠购物袋)", "condition": "always"},
        {"name": "Lock — for hostel lockers (锁/青旅柜子)", "condition": "hostel"},
        {"name": "Clothesline/hangers (晾衣绳/衣架)", "condition": "long_trip"},
    ]},
}

def get_packing_list(season: str = "summer", days: int = 3,
                      activities: list = None, international: bool = False,
                      high_altitude: bool = False, beach: bool = False,
                      road_trip: bool = False, hostel: bool = False) -> str:
    """Generate packing list text based on conditions"""
    conditions = {"always": True, "optional": True}
    conditions[season] = True
    if days >= 5: conditions["long_trip"] = True
    if international: conditions["international"] = True
    if high_altitude: conditions["high_altitude"] = True
    if beach: conditions["beach"] = True
    if road_trip: conditions["road_trip"] = True
    if hostel: conditions["hostel"] = True
    if season in ("summer",): conditions["rainy"] = True

    lines = []
    for cat_key, cat in PACKING_CATEGORIES.items():
        items = [i for i in cat["items"] if conditions.get(i["condition"], False)]
        if not items:
            continue
        lines.append(f"\n**{cat['icon']} {cat['name']}**")
        for item in items:
            lines.append(f"- {item['name']}")

    return "\n".join(lines)
